name: Deploy to App Engine

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Update YAML Files
        uses: microsoft/variable-substitution@v1
        with:
          files: "app.yaml, updater.yaml"
        env:
          API_URL: ${{ secrets.API_URL }}
          COIN_URL: ${{ secrets.COIN_URL }}
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
          SCHEDULE: ${{ secrets.SCHEDULE }}
      - name: Deploy to Default Service App Engine
        uses: actions-hub/gcloud@master
        env:
          PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
          APPLICATION_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}
        with:
          args: app deploy app.yaml
      - name: Deploy to Updater Service App Engine
        uses: actions-hub/gcloud@master
        env:
          PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
          APPLICATION_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}
        with:
          args: app deploy updater.yaml
